Working on making it support all doc types and automatically update new docs

diff --git a/xml2couchdb b/xml2couchdb
--- a/xml2couchdb
+++ b/xml2couchdb
@@ -1,26 +1,59 @@
 #!/bin/bash
 
-while read file; do
-	id=beer:$(xml sel -t -m '/beer' -v @id $file);
-	id=${id/\//:};
+# while read type; do
+	type="beer";
+# 	echo $type;
+	while read file; do
+		id=$type:$(xml sel -t -m "/$type" -v @id $file);
+		id=${id/\//:};
+		# echo $id;
 
-	if ! ./xml2json < $file | curl --silent --fail --write-out "%{http_code}" -X PUT --data-binary @- http://localhost:5984/beercrush/$id > curl.out; then
+		# id2=${file//\//:};
+		# id2=${id2%%.xml}
+		# if [ $id != $id2 ]; then
+		# 	echo "path and id differ. $id != $id2";
+		# fi
 
-		http_code=$(cat curl.out);
-		if (( $http_code != 409 )); then
-			echo $id $http_code;
+		couch_url="http://localhost:5984/beercrush/$id"
+
+		./xml2json < $file | jsontidy > $id.json;
+
+		if ! curl --silent --fail --write-out "%{http_code}" -X PUT --data-binary @- $couch_url < $id.json > curl.out; then
+		
+			http_code=$(cat curl.out);
+			if (( $http_code != 409 )); then
+				echo $id $http_code;
+			else
+
+				# Should we try to update it?
+				if ! curl --silent --fail $couch_url | jsontidy > existing.json; then
+					echo "Failed to get $couch_url";
+				else
+
+					indb_md5=$(md5sum existing.json | awk '{print $1}');
+					this_md5=$(md5sum $id.json | awk '{print $1}');
+
+					if [[ $this_md5 != $indb_md5 ]]; then
+						echo "Docs are diff: $this_md5 != $indb_md5";
+						diff -u existing.json $id.json |colordiff;
+						# Yes, they're different
+						# Get the _rev
+						rev=$(cat existing.json | php -r '$obj=json_decode(file_get_contents("php://stdin"));print $obj->_rev."\n";');
+						echo "Updating $id ($rev)";
+					else
+						# No matter
+						echo "No need to update couchdb doc";
+					fi
+					
+					rm -f existing.json;
+				fi
+			fi
 		fi
 		
-	fi
+		rm -f $id.json;
 	
-done < <(find beer -name "*.xml")
+	done < <(find $type -name "*.xml");
+	
+# done < <(find . -type d -maxdepth 1 ! -name ".*" | sed -e 's/^.\///');
 
 rm -f curl.out
-
-# beer/Dieu-Du-Ciel/Derni-re-Volont.xml:1: parser error : Document is empty
-# beer/Dieu-Du-Ciel/Equinoxe-Du-Printemps.xml:1: parser error : Document is empty
-# beer/Dieu-Du-Ciel/P-ch-Mortel.xml:1: parser error : Document is empty
-# beer/Dieu-Du-Ciel/Paienne.xml:1: parser error : Document is empty
-# beer/Dieu-Du-Ciel/Rigor-Mortis-Abt.xml:1: parser error : Document is empty
-# beer:Jolly-Pumpkin-Artisan-Ales:Luciernaga-the-Firefly 400
-# beer/New-Belgium-Brewing-Company/Lips-Of-Faith-Dunkelweiss-30.xml:1: parser error : Document is empty
